name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  php-quality:
    uses: ./.github/workflows/php-quality.yml
    secrets: inherit

  js-quality:
    uses: ./.github/workflows/js-quality.yml
    secrets: inherit

  tests:
    needs: [php-quality, js-quality]
    uses: ./.github/workflows/tests.yml
    secrets: inherit
