name: Static Analysis Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  type-coverage:
    name: Type Coverage
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.5']

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, dom, fileinfo, zip
          coverage: none
          ini-values: memory_limit=2G
          tools: composer:v2

      - name: Cache Composer dependencies
        uses: actions/cache@v6
        with:
          path: ~/.cache/composer
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader

      - name: Run Type Coverage
        run: ./vendor/bin/pest --type-coverage --min=100

  profanity-check:
    name: Profanity Check
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.5']

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, dom, fileinfo, zip
          coverage: none
          ini-values: memory_limit=2G
          tools: composer:v2

      - name: Cache Composer dependencies
        uses: actions/cache@v6
        with:
          path: ~/.cache/composer
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader

      - name: Run Profanity Check
        run: ./vendor/bin/pest --profanity --compact --language=en,es
